config/routes.rb
WRS::Application.routes.draw do

  resources :downloads, :collection => {:report => :get}
  
  resources :show_reports

  resources :styles, :member => {:export => :get},
    :collection => {:import => :post, :import => :get}

  resources :songs

  resources :songs

  resources :web_profiles

  resources :pages

  resources :members

  resources :promos

  resources :settings, :except => [:edit, :show]

  resources :fans, :collection => {:import => :post, :tag => :post, :import => :get, :export => :get}

  resources :venues

  resources :shows
  
  resources :comments

  resources :blogs, :member => {:unsubscribe => :get}

  resources :mails, :member => {:deliver => :put, :select => :get}

  resources :lyrics

  resources :entries

  resources :comments
  
  resources :sessions
  
  resources :users

  resources :blogs

  resources :fans

  resources :songs

  root :to => 'about#index'

end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :user, :foreign_key => "created_by"
  belongs_to :setting
  
  validates_presence_of :title
end

app/controllers/styles_controller.rb
YAML::add_private_type("Style") do |type, value|
  Style.new(value)
end

class StylesController < ApplicationController
  # caches_page :show
  # cache_sweeper :style_sweeper, :only => [:create, :update, :destroy]
  
  before_filter :login_required, :except => [:show]
  before_filter :set_admin

  def update_preview
    @preview = Style.new(params[:style])
    render :update do |page|
      page.replace_html 'preview', :partial => "preview"
    end
  end
  
  # GET /styles
  # GET /styles.xml
  def index
    @setting = @global_settings
    @styles = Style.find(:all, :order => "created_at DESC")
  end

  # GET /styles/1
  # GET /styles/1.xml
  def show
    @style = Style.find(params[:id])
    
    respond_to do |format|
      format.html { 
        login_required
        render_404 }
      format.css { render :layout => false }
    end
  end
  
  def export
    @style = Style.find(params[:id])
    title = @style.title.gsub(/[\.|\/| ]/, "_")
    filename = "#{title}.yml"
    send_data(
      @style.to_yaml,
      :type => 'text/yaml; charset=utf-8; header=present',
      :filename => filename)
  end
  
  # TODO: Import YAML into new Styles
  def import
    if params[:dump]
      @yaml = YAML.load(params[:dump][:file].read)
      @attributes = @yaml.ivars["attributes"]
      @attributes.delete("created_at")
      @attributes.delete("updated_at")
      @attributes.delete("created_by")
      @style = Style.new(@attributes)
      if @style.save
        flash[:notice] = 'Style was successfully created.'
        redirect_to(styles_path)
      else
        flash[:error] = "There was a problem creating the new style setting."
        render(import_styles_path)
      end
    end
  rescue
    flash[:error] = "There was a problem creating the new style setting."
    render(import_styles_path)
  end

  # GET /styles/new
  # GET /styles/new.xml
  def new
    @style = Style.new
    @preview = @style
  end

  # GET /styles/1/edit
  def edit
    @style = Style.find(params[:id])
    @preview = @style
  end

  # POST /styles
  # POST /styles.xml
  def create
    @style = Style.new(params[:style])
    @style.user = current_user
    if @style.save
      flash[:notice] = 'Style was successfully created.'
      redirect_to(styles_path)
    end
  end

  # PUT /styles/1
  # PUT /styles/1.xml
  def update
    @style = Style.find(params[:id])    
    params[:style][:user] = current_user

    if @style.update_attributes(params[:style])
      flash[:notice] = 'Style was successfully updated.'
      redirect_to(styles_path)
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.xml
  def destroy
    @style = Style.find(params[:id])
    @style.destroy

    redirect_to(styles_path)
  end
end

app/views/styles/_preview.html.erb
<style type="text/css" media="screen">
  #preview {
    background-color: #ccc;
  }
  #preview .body {    
    background: url(/images/sidebar_bg.png) <%= @preview.sidebar_bg %> top left repeat-x;
    border: 1px solid <%= @preview.main_bg %>;
    color: <%= @preview.body %>;
  }
  #preview .main {
    background:  <%= @preview.main_bg %> top left repeat-x;
    padding: 0 5px 5px 5px;
    width: 218px;
  }
  #preview div.body p.byline a,
  #preview div.body a {
    color: <%= @preview.link %>;
  }
  #preview h2.header a,  
  #preview h2.header a:visited,
  #preview .main h2.header a:hover {
    background: url(/images/header.png) <%= @preview.link %> top left repeat-x;
	  color: <%= @preview.link %>;
	  display: block;	
	  margin: 0 -5px;
	  font-weight: normal;
	  text-align: center;
	  text-transform: uppercase;
  }
  #preview h2.header a span.type,  
  #preview h2.header a:hover span.type,
  #preview h2.header a:visited span.type {    
    color: <%= @preview.news_heading %>;
  }
  
  
  #preview p.byline a:visited,
  #preview a:visited {
    color: <%= @preview.link_visited %>;
  }
  #preview div.body p.byline a:hover,
  #preview div.body a:hover {
    color: <%= @preview.link_hover %>;
  }
  #preview .main h3 {
    color: <%= @preview.heading %>;
	  font-family:Georgia,"Times New Roman",Times,serif;
  }
  #preview .main .news h3 {
    color: <%= @preview.news_heading %>;
  }
  #preview .sidebar {
    float: right;
    padding: 10px;
    width: 150px;
  }
  #preview .sidebar div.module {
    background-color: <%= @preview.module_bg %>;
    margin-bottom: 10px;
    padding: 5px;
    width: 140px;    
  }
  #preview .sidebar div.module h2 {
    background-color: <%= @preview.module_heading_bg %>;
    color: <%= @preview.module_heading %>;
	  display: block;
    margin: -5px;
	  display: block;
	  font-size: 1em;
	  font-weight: normal;
	  letter-spacing: 0.3em;
	  text-align: center;
	  text-transform: uppercase;
  }
	#preview .sidebar div.module h2 a {
	  display: block;
    padding: 3px;
	}
  #preview .sidebar div.module h2 a:hover {
    color: <%= @preview.module_heading_hover %>;
    background: url(/images/sidebar_head_bg.png) #1f5c8b top left repeat-x;
  }
  #preview .footer {
    background: url(/images/footer_bg.png) <%= @preview.footer_bg %> top left repeat-x;
    color: <%= @preview.footer %>;
    padding: 5px;
  }
  #preview .footer a {
    color: <%= @preview.footer_link %>;
  }
  #preview p.byline {
    clear: none;
    color: <%= @preview.utility %>;
  }


  #preview div.nav ul, 
	#preview div.nav {
		width: 398px;
	}

	#preview div.nav ul
  {
    background: url(/images/nav_wide_bg.png) <%= @preview.main_bg %> bottom left repeat-x;
    height: 28px;
    list-style: none;
    padding: 0;
    margin: 0;
  }
  
  #preview div.nav li
  {
    float: left;
    margin: 0;
    font-weight: normal;
  }
  
  #preview div.nav li
  {
    color: <%= @preview.utility %>;
    display: block;
    float: left;
    line-height: 2em;
    text-decoration: none;
    text-align: center;
    text-transform: uppercase;
    width: 115px;
  }
  #preview div.nav li a {
    ccolor: <%= @preview.link %>;
    display: block;
  }
  #preview div.nav li a:hover
  { 
    background: url(/images/nav_bg.png) <%= @preview.main_bg %> bottom left repeat-x;
	  ccolor: <%= @preview.link_hover %>;
  }
  
  /* Hide from IE5-Mac \*/
  #preview div.nav li a
  {
   float: none
  }
  /* End hide */

  
  .color_preview {
    border: 1px solid #ccc;
    float: left;   
    height: 22px;
    margin-right: 5px;
    width: 22px;
  }
  #preview_body {
    background: <%= @preview.body %>;
  }
  #preview_heading {
    background: <%= @preview.heading %>;
  }
  #preview_news_heading {
    background: <%= @preview.news_heading %>;
  }
  #preview_link {
    background: <%= @preview.link %>;
  }
  #preview_link_visited {
    background: <%= @preview.link_visited %>;
  }
  #preview_link_hover {
    background: <%= @preview.link_hover %>;
  }
  #preview_utility {
    background: <%= @preview.utility %>;
  }
  #preview_main_bg {
    background: <%= @preview.main_bg %>;
  }
  #preview_sidebar_bg {
    background: <%= @preview.sidebar_bg %>;
  }
  #preview_module_bg {
    background: <%= @preview.module_bg %>;
  }
  #preview_module_heading {
    background: <%= @preview.module_heading %>;
  }
  #preview_module_heading_hover {
    background: <%= @preview.module_heading_hover %>;
  }
  #preview_module_heading_bg {
    background: <%= @preview.module_heading_bg %>;
  }
  #preview_module_heading_bg_hover {
    background: <%= @preview.module_heading_bg_hover %>;
  }
  #preview_footer {
    background: <%= @preview.footer %>;
  }
  #preview_footer_link {
    background: <%= @preview.footer_link %>;
  }
  #preview_footer_bg {
    background: <%= @preview.footer_bg %>;
  }
  

</style>

<h3>Preview:</h3>
<div class="body">
  <div class="nav">
    <ul>
        <li><a href="#">News</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Shows</a></li>
    </ul>
  </div> <!-- end DIV "nav" -->
    
  <div class="sidebar">
    <div class="module">
    <h2><a href="#">Heading</a></h2>
    <p>Module text</p>
    <p>Text with a <a href="#">link</a>.</p>
    </div> <!-- end DIV "module" -->
    <div class="module">
    <h2><a href="#">Shows</a></h2>
    <p>More module text</p>
    <p>Text with <a href="#">another link</a>.</p>
    </div> <!-- end DIV "module" -->
  </div> <!-- end DIV "preview_sidebar" -->
  
  <div class="main">
    <div class="news">
    <h2 class="header"><a href="#">Some <span class="type">News</span></a></h2>   
    <h3>Newsflash!</h3>
    <p>It's a news entry about some news that happened to the band!</p>
    <p class="byline">posted on <%= Time.now.strftime("%b %d %Y") %> by <strong><a href="#">jeff</a></strong>. (<a href="#">edit</a> | <a href="#">delete</a>)</p>
    </div> <!-- end DIV "news" -->
    <h2 class="header"><a href="#">Some <span class="type">Blogs</span></a></h2>
    <h3>Blog item: Hooray for penguins!</h3>
    <p>It's an item about penguins and how great they are.  Aren't they great?  Don't you love penguins?</p>
    <p class="byline">posted on <%= Time.now.strftime("%b %d %Y") %> by <strong><a href="#">jeff</a></strong>. <a href="#">4 comments</a>. (<a href="#">edit</a> | <a href="#">delete</a>)</p>
  </div> <!-- end DIV "preview_main" -->
  <div class="footer">
    <p>Footer text</p>
    <p><a href="#">Footer link</a></p>
  </div> <!-- end DIV "footer" -->

</div> <!-- end DIV "preview_body" -->

app/views/styles/edit.html.erb
<% @page_title = "Edit Styles" %>

<div id="edit_style" class="style">

<%= error_messages_for :style %>

<% form_for(@style) do |f| %>
  
  <dl>
    <dt><%= f.text_field :title %></dt>
    <dd class="label">Title</dd>
    <dd class="description">Name of this style profile</dd>
  </dl>  
  <h2 id="foreground_styles">Main styles</h2>
  <dl class="foregrounds">
    <dt><div class="style_preview" id="preview_body"></div>
      <%= f.text_field :body %></dt>
    <dd class="label">Body text</dd>
    <dd class="description">Foreground style for standard text</dd>
    
    <dt><div class="style_preview" id="preview_heading"></div>
      <%= f.text_field :heading %></dt>
    <dd class="label">Heading style</dd>
    <dd class="description">Foreground style for standard headings (blog titles, lyric titles, &amp;c.)</dd>
    
    <dt><div class="style_preview" id="preview_news_heading"></div>
      <%= f.text_field :news_heading %></dt>
    <dd class="label">News entry heading style</dd>
    <dd class="description">Foreground style for titles of news headings</dd>
    
    <dt><div class="style_preview" id="preview_link"></div>
      <%= f.text_field :link %></dt>
    <dd class="label">Link style</dd>
    <dd class="description">Foreground style for standard text links</dd>
    
    <dt><div class="style_preview" id="preview_link_visited"></div>
      <%= f.text_field :link_visited %></dt>
    <dd class="label">Visited link style</dd>
    <dd class="description">Fireground style for visited text links</dd>
    
    <dt><div class="style_preview" id="preview_link_hover"></div>
      <%= f.text_field :link_hover %></dt>
    <dd class="label">Link hover style</dd>
    <dd class="description">Foreground hover style for standard text links</dd>
    
    <dt><div class="style_preview" id="preview_utility"></div>
      <%= f.text_field :utility %></dt>
    <dd class="label">Utility text style</dd>
    <dd class="description">Foreground style for utility text (blog entry bylines, &amp;c.)</dd>
  </dl>
  <h2 id="background_styles">Background styles</h2>
  <dl class="backgrounds">
    <dt><div class="style_preview" id="preview_main_bg"></div>
      <%= f.text_field :main_bg %></dt>
    <dd class="label">Main background</dd>
    <dd class="description">Background style for main content area</dd>
    
    <dt><div class="style_preview" id="preview_sidebar_bg"></div>
      <%= f.text_field :sidebar_bg %></dt>
    <dd class="label">Sidebar background</dd>
    <dd class="description">Background style for sidebar</dd>
  </dl>
  <h2 id="module_styles">Module styles</h2>  <dl class="modules">
    
    <dt><div class="style_preview" id="preview_module_bg"></div>
      <%= f.text_field :module_bg %></dt>
    <dd class="label">Module background</dd>
    <dd class="description">Background style for sidebar modules</dd>
    
    <dt><div class="style_preview" id="preview_module_heading"></div>
      <%= f.text_field :module_heading %></dt>  
    <dd class="label">Module heading style</dd>
    <dd class="description">Foreground style for module headings</dd>
    
    <dt><div class="style_preview" id="preview_module_heading_hover"></div>
      <%= f.text_field :module_heading_hover %></dt>
    <dd class="label">Module heading hover style</dd>
    <dd class="description">Foreground style for hover text on module headings</dd>
    
    <dt><div class="style_preview" id="preview_module_heading_bg"></div>
      <%= f.text_field :module_heading_bg %></dt>
    <dd class="label">Module heading background</dd>
    <dd class="description">Background style for module headings</dd>
    
    <dt><div class="style_preview" id="preview_module_heading_bg_hover"></div>
      <%= f.text_field :module_heading_bg_hover %></dt>
    <dd class="label">Module heading hover background</dd>
    <dd class="description">Background hover style for module headings</dd>
  </dl>
  <h2 id="footer_styles">Footer styles</h2>
  <dl class="footer">
    <dt><div class="style_preview" id="preview_footer"></div>
      <%= f.text_field :footer %></dt>
    <dd class="label">Footer text style</dd>
  		<dd class="description">Foreground style for footer</dd>
    
    <dt><div class="style_preview" id="preview_footer_link"></div>
      <%= f.text_field :footer_link %></dt>
    <dd class="label">Footer link style</dd>
  		<dd class="description">Link style for footer</dd>
    
    <dt><div class="style_preview" id="preview_footer_bg"></div>
      <%= f.text_field :footer_bg %></dt>
    <dd class="label">Footer background style</dd>
  		<dd class="description">Background style for footer</dd>
  </dl>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>
</div>

<div id="preview">
  <%= render :partial => 'preview' %>
</div> <!-- end DIV "preview" -->



<%= observe_form("edit_style_#{@style.id}", :frequency => 1, :on => 'change', :url => { :action => :update_preview }, :with => {:id => @style.id}) %>

app/views/styles/import.html.erb
<% @page_title = "Import Styles" %>

<h1>Import styles from YAML file</h1>

 <% form_for :dump, :url=>{:controller=>"styles", :action=>"import"}, :html => { :multipart => true } do |f| -%>
 <tableî>
   <tr>
     <td>
      <label for="dump_file">
        Select a YAML File :
      </label>
     </td>
     <td >
       <%= f.file_field :file -%>
     </td>
   </tr>
   <tr>
     <td colspan='2'>
       <%= submit_tag "Submit" -%>
     </td>
   </tr>
 </table>
<% end -%>

app/views/styles/index.html.erb
<% @page_title = "Styles" %>

<div id="styles">

<h1>Styles</h1>

<p><%= link_to 'New styles', new_style_path %> | <%= link_to 'Import styles', import_styles_path %></p>

<p>Choose style scheme: <br />

<% form_for(@setting) do |f| %>
  
<%= f.collection_select :style_id, Style.find(:all), :id, :title, :prompt => true %>
 
    <%= f.submit "Update" %>
<% end %></p>

<% for @style in @styles %>
<% @style.user = current_user if @style.user.blank? %>
<div class="style">
<h3 class="post_title"><%= @style.title %></h3>
  <p class="byline"> 
posted on <%= @style.created_at.strftime("%b %d %Y") %> by <strong><%= link_to(@style.user.full_name, styles_path(:author => @style.user.full_name)) %></strong>.
      (<%= link_to "edit", edit_style_path(@style) %> | <%= link_to "export", export_style_path(@style) %> | <%= link_to 'delete', @style, :confirm => 'Are you sure?', :method => :delete %>)
  </p>
</div>
<% end %>  
</div> <!-- end DIV "styles" -->

app/views/styles/new.html.erb
<% @page_title = "New Styles" %>

<div id="new_style" class="style">
  
<h1>New Styles</h1>

<%= error_messages_for :style %>

<% form_for(@style) do |f| %>
  
  <dl>
    <dt><%= f.text_field :title %></dt>
    <dd class="label">Title</dd>
    <dd class="description">Name of this style profile</dd>
  </dl>  
  
  <h2 id="foreground_colors">Main colors</h2>
  <dl class="foregrounds">    
    <dt><div class="color_preview" id="preview_body"></div>
      <%= f.text_field :body %></dt>
    <dd class="label">Body text</dd>
    <dd class="description">Foreground color for standard text</dd>
    
    <dt><div class="color_preview" id="preview_heading"></div>
      <%= f.text_field :heading %></dt>
    <dd class="label">Heading color</dd>
    <dd class="description">Foreground color for standard headings (blog titles, lyric titles, &amp;c.)</dd>
    
    <dt><div class="color_preview" id="preview_news_heading"></div>
      <%= f.text_field :news_heading %></dt>
    <dd class="label">News entry heading color</dd>
    <dd class="description">Foreground color for titles of news headings</dd>
    
    <dt><div class="color_preview" id="preview_link"></div>
      <%= f.text_field :link %></dt>
    <dd class="label">Link color</dd>
    <dd class="description">Foreground color for standard text links</dd>
    
    <dt><div class="color_preview" id="preview_link_visited"></div>
      <%= f.text_field :link_visited %></dt>
    <dd class="label">Visited link color</dd>
    <dd class="description">Fireground color for visited text links</dd>
    
    <dt><div class="color_preview" id="preview_link_hover"></div>
      <%= f.text_field :link_hover %></dt>
    <dd class="label">Link hover color</dd>
    <dd class="description">Foreground hover color for standard text links</dd>
    
    <dt><div class="color_preview" id="preview_utility"></div>
      <%= f.text_field :utility %></dt>
    <dd class="label">Utility text color</dd>
    <dd class="description">Foreground color for utility text (blog entry bylines, &amp;c.)</dd>
  </dl>
  <h2 id="background_colors">Background colors</h2>
  <dl class="backgrounds">
    <dt><div class="color_preview" id="preview_main_bg"></div>
      <%= f.text_field :main_bg %></dt>
    <dd class="label">Main background</dd>
    <dd class="description">Background color for main content area</dd>
    
    <dt><div class="color_preview" id="preview_sidebar_bg"></div>
      <%= f.text_field :sidebar_bg %></dt>
    <dd class="label">Sidebar background</dd>
    <dd class="description">Background color for sidebar</dd>
  </dl>
  <h2 id="module_colors">Module colors</h2>  <dl class="modules">
    
    <dt><div class="color_preview" id="preview_module_bg"></div>
      <%= f.text_field :module_bg %></dt>
    <dd class="label">Module background</dd>
    <dd class="description">Background color for sidebar modules</dd>
    
    <dt><div class="color_preview" id="preview_module_heading"></div>
      <%= f.text_field :module_heading %></dt>  
    <dd class="label">Module heading color</dd>
    <dd class="description">Foreground color for module headings</dd>
    
    <dt><div class="color_preview" id="preview_module_heading_hover"></div>
      <%= f.text_field :module_heading_hover %></dt>
    <dd class="label">Module heading hover color</dd>
    <dd class="description">Foreground color for hover text on module headings</dd>
    
    <dt><div class="color_preview" id="preview_module_heading_bg"></div>
      <%= f.text_field :module_heading_bg %></dt>
    <dd class="label">Module heading background</dd>
    <dd class="description">Background color for module headings</dd>
    
    <dt><div class="color_preview" id="preview_module_heading_bg_hover"></div>
      <%= f.text_field :module_heading_bg_hover %></dt>
    <dd class="label">Module heading hover background</dd>
    <dd class="description">Background hover color for module headings</dd>
  </dl>
  <h2 id="footer_colors">Footer colors</h2>
  <dl class="footer">
    <dt><div class="color_preview" id="preview_footer"></div>
      <%= f.text_field :footer %></dt>
    <dd class="label">Footer text color</dd>
  		<dd class="description">Foreground color for footer</dd>
    
    <dt><div class="color_preview" id="preview_footer_link"></div>
      <%= f.text_field :footer_link %></dt>
    <dd class="label">Footer link color</dd>
  		<dd class="description">Link color for footer</dd>
    
    <dt><div class="color_preview" id="preview_footer_bg"></div>
      <%= f.text_field :footer_bg %></dt>
    <dd class="label">Footer background color</dd>
  		<dd class="description">Background color for footer</dd>
  </dl>
  <p><%= f.submit "Create" %></p>
<% end %>

</div>



<div id="preview">
  <%= render :partial => 'preview' %>
</div> <!-- end DIV "preview" -->



<%= observe_form("new_style", :frequency => 1, :on => 'change', :url => { :action => :update_preview }, :with => {:id => @style.id}) %>

app/views/styles/show.css.erb
  body, html {
    color: <%= @style.body %>;
  }

  h1.header span.type, 
	#news h3.post_title a {
    color: <%= @style.news_heading %>;
	}
	
	#sidebar div.module,
  #shows .show_date h3,
  #shows .show_date .time,
  #shows .show_date .address,
	h1.header a, 
	h1.header a:visited,
  a {
    color: <%= @style.link %>;
  }
  a:visited {
    color: <%= @style.link_visited %>;
  }
  a:hover,  
	#news h3.post_title a:hover {
    color: <%= @style.link_hover %>;
  }
	
	#archive h2,
	p.byline, 	
  .lyric h4.composer {
    color: <%= @style.utility %>;
	}
	#archive h2 {
	  border-bottom: 1px solid <%= @style.utility %>;
  }
	
	#main {
    background-color: <%= @style.main_bg %>;
	}
	
	#sidebar {
    background-color: <%= @style.sidebar_bg %>;
	}
	#sidebar div.module {
    background-color: <%= @style.module_bg %>;
	}
	#inside-wrap {
    background: url(/images/sidebar_bg.png) <%= @style.sidebar_bg %> top left repeat-x;
    border: 1px solid <%= @style.main_bg %>;
	}
	
	
	#nav ul
  {
    background: url(/images/nav_wide_bg.png) <%= @style.main_bg %> bottom left repeat-x;
  }
  #nav li
  {
    color: <%= @style.utility %>;
  }
  #nav li a:hover
  { 
    background: url(/images/nav_bg.png) <%= @style.main_bg %> bottom left repeat-x;
  }
  
  
  input#email, input#zip_code {    
    border: 1px solid black;
    background-color: <%= @style.sidebar_bg %>;
    color: <%= @style.main_bg %>;
  }
  #mailing_list {
    color: <%= @style.main_bg %>;
  }
	
	
	#sidebar div.module h2,
	#sidebar div.module h2 a,
	#sidebar div.module h2 a:visited {
    background-color: <%= @style.module_heading_bg %>; 
    color: <%= @style.module_heading %>;
	}
  
  
	
	#sidebar div.module h2:hover a,
	#sidebar div.module h2:hover a:hover,
	#sidebar div.module h2:hover {
    background: url(/images/sidebar_head_bg.png) <%= @style.module_heading_bg_hover %> top left repeat-x;
	  color: <%= @style.module_heading_hover %>;
	}
  
  #footer {
    background-color: <%= @style.footer_bg %>;
  }
  
  #footer, 
	#footer #copyright_notice {
    color: <%= @style.footer %>;
  }
	
  #footer a,
  #footer a:visited {    
    color: <%= @style.footer_link %>;
  }
  
  
	#fans #fans_list table td.tags a,	
	#fans #fans_list table td.tags a:visited {
	  color: <%= @style.news_heading %>;
	}
	#fans #fans_list table td.tags a:hover {
	  background-color: <%= @style.news_heading %>;
	  color: <%= @style.main_bg %>;
	}
	
	ul.twitter li {
  	color: <%= @style.body %>;
	}
  ul.twitter li.created_at {
    color: <%= @style.utility %>;
  }
  