config/routes.rb
WRS::Application.routes.draw do

  resources :downloads, :collection => {:report => :get}
  
  resources :show_reports

  resources :styles, :member => {:export => :get},
    :collection => {:import => :post, :import => :get}

  resources :songs

  resources :songs

  resources :web_profiles

  resources :pages

  resources :members

  resources :promos

  resources :settings, :except => [:edit, :show]

  resources :fans, :collection => {:import => :post, :tag => :post, :import => :get, :export => :get}

  resources :venues

  resources :shows
  
  resources :comments

  resources :blogs, :member => {:unsubscribe => :get}

  resources :mails, :member => {:deliver => :put, :select => :get}

  resources :lyrics

  resources :entries

  resources :comments
  
  resources :sessions
  
  resources :users

  resources :blogs

  resources :fans

  resources :songs

  root :to => 'about#index'

end

app/models/fan.rb
require 'digest/sha1'

class Fan < ActiveRecord::Base
  # acts_as_taggable
  
  has_many :downloads
  
	validates_presence_of :email, :zipcode
	# # validates_email_veracity_of :email
	validates_uniqueness_of :email, :case_sensitive => false
		
	before_save :encrypt_email
	before_create :set_active
	
  scope :created_since, lambda {|since_date| {:conditions => ["created_at >= ?", since_date]}}
  scope :unsubscribed_since, lambda {|since_date| {:conditions => ["unsubscribed_at >= ?", since_date]}}
  scope :active, :conditions => {:active => true}
  scope :unsubscribed, :conditions => ["active <> ?", true]
	
	def tag	  
  end
  
  def list_tags
    self.tag_list.join(" ")
  end
  
  def list_tags= list
    list = list.gsub(',',' ')
    self.tag_list = list.split.join(" ")   
  end
		
	def name= full_name
	  unless full_name.nil?
      full_name = full_name.split
      firstname = full_name.delete_at(0)
      lastname = full_name.join(' ')
      self.firstname = firstname
      self.lastname = lastname
    end
	end
	
	def self.find_tagged list
	  list = list.gsub(',',' ')
	  self.find_tagged_with(list, :match_all => true)
	end
	
	def name
	  [firstname, lastname].join(' ')
  end
  
  def name_and_email
    if name.blank?
      email
    else
      "#{name} (#{email})"
    end
  end
  
  def address
    [[city, state].join(', '), zipcode].join(' ')
  end
  
  def deactivate
    update_attributes(:active => false, :unsubscribed_at => Time.now)
  end
	
	def self.search(search, page)
	  search.strip!
    if search
      if search.match(/^tags: /)
        tags = search.gsub(/^tags:/, "")
        tags.gsub!(",", " ")
        tags = tags.split
        paginate_tagged_with(tags, :match_all => true, :order => 'created_at DESC', :page => page)
      else
        search = "%#{search}%"
        paginate :per_page => 25, :page => page,
          :conditions => ['firstname LIKE ? OR lastname LIKE ? OR email LIKE ? OR zipcode LIKE ?', search, search, search, search],
          :order => 'created_at DESC'
      end
    else
      find(:all)
    end
  end
  
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end
  
  # Encrypts the email with the user salt
  def encrypt(password)
    self.class.encrypt(email, salt)
  end
  
  protected
    def set_active
      self.active = true
    end

    def encrypt_email
      return if email.blank?
      self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{email}--") if new_record?
      self.crypted_email = encrypt(email)
    end
end

app/controllers/fans_controller.rb
require 'faster_csv'

class FansController < ApplicationController
  protect_from_forgery :except => [:new, :create]
  before_filter :load_sidebar, :except => [:create, :update, :destroy, :tag, :new_tag]
  before_filter :login_required, :only => [:index, :import, :manage]
  before_filter :body_style
  before_filter :use_crypted_email, :only => [:show, :update, :edit, :destroy, :unsubscribe]
  before_filter :set_admin
  
  DEFAULT_ZIPCODE = 78701
  
  def update_select 
    fan_list = get_fans(params[:fans])
    
    fans = Fan.find(fan_list)
    @tags = []
    
    fans.each do |fan|
      @tags << fan.tag_list
    end
    @remove_tags = @tags.flatten.uniq
    render :update do |page|      
      page.replace_html 'tag_options', :partial => 'tag_options', :locals => {:remove_tags => @remove_tags}
    end
  end
  
  def check_all
    render :update do |page|
       page.select('#tag_fans input[type=checkbox]').each do |item|
        item.checked = true
      end
    end
  end
  
  def check_none
    render :update do |page|
       page.select('#tag_fans input[type=checkbox]').each do |item|
        item.checked = false
      end
    end
  end
  
  def new_tag
    if params[:tag] == "New tag"
      render :update do |page|
        session[:fans] = params[:fans]
        unless params[:fans].empty?
          page.call("x_add_tag")
          session[:fans] = nil
        end
      end
    else
      render nil, :layout => false
    end
  end
  
  def tag
    fans = get_fans(params[:fans])
    
    if fans.empty?
      return
    else
      if params[:update]
        if params[:tag] == "New tag"
          render :update do |page|
            unless fans.empty?
              page.call("x_add_tag", fans.join("+"))
            end
          end
          return
        else
          if ["Apply tag", "Remove tag", "New tag"].include?(params[:tag])
            return
          else
            process_tag fans, params[:tag]
          end
        end 
      elsif params[:delete]
        Fan.destroy(fans)
      end
      render :update do |page|
        @fans = Fan.paginate :all, :per_page => 25, :page => params[:p], :order => "created_at DESC"
        page.replace_html 'fans_list', :partial => 'fans_list', :locals => {:fans => @fans, :fan_total => Fan.count(:all), :fan_count => @fans.length} 
      end
    end
  end
  
  def add_tag
    fans = get_fans(params[:fans])
  end


  # if user has the crypted email string, they're authorized to 
  # show, edit, destroy, etc, their account.  
  # 
  # if not, they must be logged in.
  #
  def use_crypted_email
    begin
      if params[:f] || login_required
        @fan = Fan.find(:first, :conditions => ["id = ? AND crypted_email = ?", params[:id], params[:f]])  
      end
      if @fan.nil? && login_required
        @fan = Fan.find(params[:id])
      end
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Fan not found."
      redirect_to home_path
    end
  end
  
  def body_style
    @body_style = "fans"
  end
  
  # GET /fans
  # GET /fans.xml 
  def index
    @fans = []
    @show_sidebar = false    
    @fan_total = Fan.active.count
    if params[:tag]
      @fans = Fan.active.paginate_tagged_with(params[:tag], :page => params[:p])
    elsif params[:search]
      @fans = Fan.active.search(params[:search], params[:p])
    elsif @fans.empty?
      if params[:sort]
        order_by = params[:sort]
      else
        order_by = "created_at DESC"
      end
      @fans = Fan.active.paginate :all, :per_page => 25, :page => params[:p], :order => order_by
    end
    @fan_count = @fans.length
    if @fans.empty?
      flash[:notice] = "No fans found."
    end
  end
    
  # GET /fans/import
  # POST /fans/import
  def import
    if params[:dump]
      @parsed_file = FasterCSV.parse(params[:dump][:file])
      @n=0
      @parsed_file.each do |row|
        fan = Fan.new(:name => row[0], :email => row[1], :zipcode => DEFAULT_ZIPCODE)
        if fan.save
          Mailer.send_later(:deliver_signup_confirmation, fan)
          Mailer.send_later(:deliver_signup_report, fan)
          
          @n=@n+1
          GC.start if @n%50==0
        end
      end
      if @n > 0
        flash[:notice] = "CSV Import Successful. #{@n} new fans added."
      else
        flash[:notice] = "CSV Import: No new fans added."
      end
      redirect_to fans_path
    end
  end
  
    
  # GET /fans/export
  # POST /fans/export
  def export
    @fans = Fan.active.find(:all)

    csv_string = FasterCSV.generate do |csv|
      csv << ["Name", "E-mail", "Notes", "Section 1 - Description", "Section 1 - Email", "Section 1 - IM", "Section 1 - Phone", "Section 1 - Mobile", "Section 1 - Pager", "Section 1 - Fax", "Section 1 - Company", "Section 1 - Title", "Section 1 - Other", "Section 1 - Address"]

      for fan in @fans
        csv << [fan.name,
                fan.email,
                "", "", "", "", "", "", "", "", "", "", "",
                fan.address                
                ]
      end
    end

    # filename = @list.name.downcase.gsub(/[^0-9a-z]/, "_") + ".csv"
    filename = "fans.csv"
    send_data(csv_string,
      :type => 'text/csv; charset=utf-8; header=present',
      :filename => filename)
  end

  # GET /fans/1
  # GET /fans/1.xml
  def show
  end

  # GET /fans/new
  # GET /fans/new.xml
  def new
    @fan = Fan.new(:email => params[:email])
  end

  # GET /fans/1/edit
  def edit
  end

  # POST /fans
  # POST /fans.xml
  def create
    @fan = Fan.new(params[:fan])
    
    valid_recaptcha = !@global_settings.use_captcha_for_fans? || (!params[:homepage] && verify_recaptcha(:model => @fan))

    if valid_recaptcha && @fan.save
      Mailer.send_later(:deliver_signup_confirmation, @fan)
      Mailer.send_later(:deliver_signup_report, @fan)
      flash[:registration] = "Thanks for joining the #{@global_settings.artist_name} mailing list, #{@fan.email}.  If you'd like to tell us your name, you can do it here."
      redirect_to edit_fan_path(@fan, :f => @fan.crypted_email)
    else
      if params[:homepage]
        flash[:registration] = "You are almost done signing up for the World Racketeering Squad mailing list. Please fill in the CAPTCHA below to complete your signup."
      end
      render :action => "new"
    end
  end

  # PUT /fans/1
  # PUT /fans/1.xml
  def update
    if @fan.update_attributes(params[:fan])
      flash[:notice] = 'Fan was successfully updated.'
      redirect_to(fan_path(@fan, :f => @fan.crypted_email))
    else
      render :action => "edit"
    end
  end
  
  def unsubscribe
  end

  # DELETE /fans/1
  # DELETE /fans/1.xml
  def destroy
    Mailer.deliver_unsubscribe_report(@fan)
    @fan.deactivate
    flash[:notice] = "#{@fan.email} was successfully unsubscribed."

    if logged_in?
      redirect_to fans_path
    else
      redirect_to home_path
    end
  end
  
  protected
  
  def process_tag fans, tag
    for f in fans
      fan = Fan.find(f)
      
      if tag.match(/^remove /)      
        fan.tag_list.remove(tag.gsub("remove ",""))
      else             
        fan.tag_list.add(tag) unless ["Apply tag", "Remove tag", "New tag"].include?(tag)
      end
      fan.save
    end
  end
  
  def get_fans fans
    if fans && fans.is_a?(Hash)
      fans = fans.keys
    end
    if fans && fans.is_a?(String)
      fans = fans.split("+")
    end
    fans || []
  end
end

app/helpers/fans_helper.rb
module FansHelper
end

app/views/fans/_fans_list.html.erb
<% form_remote_for :fan, :url => { :action => "tag" }, :html => {:id => 'tag_fans'} do |f| %>

<p class="tag_options">Select: <%= link_to_remote "All", :url => { :action => "check_all" } %> | <%= link_to_remote "None", :url => { :action => "check_none" } %> 
    
   | <%= link_to "Import Fans", import_fans_path %> | 
    <%= link_to "Export Fans", export_fans_path %> | 
  
    <%= submit_tag('Delete', :name => 'delete') %>  


  Listing <%= fan_count %> of <%= pluralize(fan_total, "fan") %>.
  
</p>


<table>
  <tr>
    <th class="check"></th>
    <th class="first"><%= link_to "First", fans_path(:sort => "Firstname") %></th>
    <th class="last"><%= link_to "Last", fans_path(:sort => "Lastname") %></th>
    <th class="email"><%= link_to "Email", fans_path(:sort => "Email") %></th>
    <th class="city"><%= link_to "City", fans_path(:sort => "City") %></th>
    <th class="state"><%= link_to "State", fans_path(:sort => "State") %></th>
    <th class="zipcode"><%= link_to "ZIP", fans_path(:sort => "Zipcode") %></th>
    <th class="created_at"><%= link_to "Joined", fans_path(:sort => "created_at") %></th>
  </tr>

<% unless fans.empty? %>
  <% for fan in fans %>
    <tr>
      <td class="check"><%= check_box_tag "fans[#{fan.id}]", fan.id %></td>
      <td class="first"><%=h fan.firstname %></td>
      <td class="last"><%=h fan.lastname %></td>
      <td class="email"><%= link_to fan.email, edit_fan_path(fan) %></td>
      <td class="city"><%= fan.city %></td>
      <td class="state"><%=h fan.state %></td>
      <td class="zipcode"><%=h fan.zipcode %></td>
      <td class="created_at"><%= fan.created_at.strftime("%b %d %Y") unless fan.created_at.nil? %></td>
    </tr>
  <% end %>
<% end %>
</table>

<% end %> <!-- form -->

<p><%= will_paginate @fans %></p>



<%
  observe_form("tag_fans", :on => :change, :frequency => 1, :url => {:action => :update_select})
%>
 
 
 
 

app/views/fans/_tag_options.html.erb
<% remove_tags ||= [] %>
  <% 
    select_options = []
    select_options << content_tag('option',"Apply tag")    
    Fan.tag_counts.each do |tag|
      select_options << "<option class='tag'>#{tag}</option>"
    end
    unless remove_tags.empty?
      select_options << content_tag('option',"Remove tag")
      remove_tags.each do |tag|
        select_options << "<option class='remove' value='remove #{tag}'>#{tag}</option>"
      end
    end
    select_options << content_tag('option', "New tag")
  %>  
  
  <%= select_tag :tag, select_options.join, :id => "tag_select" %>
  
  <% submit_tag('Update', :name => '_commit',
                :onclick => "Form.getInputs(this.form, null, 
                'commit')[0].value = 'Update'") %>
  
  
<%=
  observe_field("tag_select", :on => :select, :frequency => 2, :url => {:action => :tag, :update => 'Update'}, :with => "Form.serialize($('tag_fans'))")
%>

app/views/fans/edit.html.haml
- @page_title = "Edit Fan"

%h1 
  Edit Fan

#registration
  - if flash[:registration]
    %h4= flash[:registration]
    
  - if @global_settings.free_download?
    %p 
      To thank you for joining our mailing list, we're offering a 
      %strong= link_to("free download", downloads_url(:email => @fan.email))
      of our song, 
      = "\"#{@global_settings.free_download_name}\"."
      = link_to("Download it now.", downloads_url(:email => @fan.email))
    
= error_messages_for :fan

- form_for(@fan, :url => fan_path(@fan, :f => @fan.crypted_email), :html => {:method => :put}) do |f|

  %p
    = f.label :firstname, "First Name"
    %br
    = f.text_field :firstname

  %p
    =f.label :lastname, "Last Name"
    %br
    =f.text_field :lastname  

  %p
    =f.label :city
    %br
    =f.text_field :city
  
  %p
    =f.label :state
    %br
    =f.text_field :state
  
  %p
    =f.label :zipcode
    %br
    =f.text_field :zipcode
  
  %p
    =f.submit "Update"

app/views/fans/index.html.erb
<% @page_title = "Fans" %>

<div id="fans">


<% form_tag fans_path, :method => 'get' do %>
  <p>Search fans 
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<h1>Listing fans</h1>

<div id="fans_list">
  <%= render :partial => "fans_list", :locals => {:fans => @fans, :fan_count => @fan_count, :fan_total => @fan_total} %>

</div> <!-- end DIV "fans_list" -->


</div> <!-- end DIV "fans" -->


<%= javascript_tag %Q{
  function x_add_tag(fans)
  {
    var tag = prompt('Name for new tag', '');
    if (tag == null) return;
    #{remote_function :url => tag_fans_path(:fans => @fans_to_tag, :update => "update"), :with => "'tag=' + tag + '&fans=' + fans" }  
  }

} %>

app/views/fans/new.html.haml
- @page_title =  "New Fan" 

#fans

  %h1 New fan
  
  - if flash[:registration]
    %h4= flash[:registration]
  
  - if @global_settings.free_download?
    %p 
      Enter your information below to be 
      %strong taken to your free download.  
      Thanks!
  
  = error_messages_for :fan 

  - form_for(@fan) do |f| 
  
    %p
      = f.label :firstname, "First Name"
      = f.text_field :firstname 
  
    %p
      = f.label :lastname, "Last Name"
      = f.text_field :lastname 
  
    %p
      = f.label :email
      = f.text_field :email

    %p
      = f.label :zipcode
      = f.text_field :zipcode 
  
    - if @global_settings.use_captcha_for_fans?
      #captcha
        = recaptcha_tags 
    
    %p
      = f.submit "Create" 
  

app/views/fans/show.html.haml
- # TODO: Prettify design for Fan#show
- # TODO: Show tags, allow deleting of tags

-@page_title = @fan.name

%p
  %b= "First Name: #{@fan.firstname}"

%p
  %b= "Last Name: #{@fan.lastname}"

%p
  %b= "Email: #{@fan.email}"

%p
  %b= "City: #{@fan.city}"

%p
  %b= "State: #{@fan.state}"

%p
  %b= "Zipcode: #{@fan.zipcode}"

app/views/fans/unsubscribe.html.erb
<% @page_title = "Unsubscribe" %>

<h1>Unsubscribe</h1>

<p>Click the button below to unsubscribe <strong><%= @fan.email %></strong> from the <%= @global_settings.artist_name %> mailing list.</p>

<% form_for(@fan, :url => fan_path(@fan, :f => @fan.crypted_email), :html => {:method => :delete}) do |f| %>
  <p>
    <%= submit_tag "Unsubscribe" %>
  </p>
<% end %>