config/routes.rb
WRS::Application.routes.draw do

  resources :downloads, :collection => {:report => :get}
  
  resources :show_reports

  resources :styles, :member => {:export => :get},
    :collection => {:import => :post, :import => :get}

  resources :songs

  resources :songs

  resources :web_profiles

  resources :pages

  resources :members

  resources :promos

  resources :settings, :except => [:edit, :show]

  resources :fans, :collection => {:import => :post, :tag => :post, :import => :get, :export => :get}

  resources :venues

  resources :shows
  
  resources :comments

  resources :blogs, :member => {:unsubscribe => :get}

  resources :mails, :member => {:deliver => :put, :select => :get}

  resources :lyrics

  resources :entries

  resources :comments
  
  resources :sessions
  
  resources :users

  resources :blogs

  resources :fans

  resources :songs

  root :to => 'about#index'

end

app/models/promo.rb
class Promo < ActiveRecord::Base
  belongs_to :setting
  
  validates_presence_of :title, :body
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_filter :login_required
  before_filter :set_admin
  
  # GET /promos
  # GET /promos.xml
  def index
    @setting = @global_settings
    @promos = Promo.find(:all, :order => "created_at DESC")
  end

  # GET /promos/1
  # GET /promos/1.xml
  def show
    @promo = Promo.find(params[:id])

  end

  # GET /promos/new
  # GET /promos/new.xml
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
    @promo = Promo.find(params[:id])
  end
  
  # POST /promos
  # POST /promos.xml
  def create
    @promo = Promo.new(params[:promo])

    if params[:preview_button] || !@promo.save
      render :action => "new"
    else
      @global_settings.promo = @promo
      @global_settings.save
      flash[:notice] = 'Promo was successfully created.'
      redirect_to(@promo)
    end
  end

  # PUT /promos/1
  # PUT /promos/1.xml
  def update
    @promo = Promo.find(params[:id])

    if !@promo.update_attributes(params[:promo]) || params[:preview_button]
      render :action => "edit"
    else
      flash[:notice] = 'Promo was successfully updated.'
      redirect_to(@promo)
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.xml
  def destroy
    @promo = Promo.find(params[:id])
    @promo.destroy
    redirect_to(promos_url) 
  end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_promo.html.erb
<p>
  <b>Title:</b>
  <%=h @promo.title %>
</p>

<p>
  <b>Body:</b>
  <%= @promo.body %>
</p>

app/views/promos/edit.html.erb
<% @page_title = "Edit Promo" %>

<%= javascript_include_tag :fckeditor %>
<h1>Edit Promo</h1>

  <% if params[:preview_button] %>
    <%= render :partial => @promo %>
  <% end %>


<%= error_messages_for :promo %>

<% form_for(@promo) do |f| %>
  <p>
		<%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

    <%= fckeditor_tag("promo", "body", :height => "500px", :width => "600px") %>
  <p>
    <%= f.submit "Preview", :name => "preview_button" %>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<% @page_title = "Promos" %>

<h1>Promos</h1>
<p>A <strong>Promo</strong> is a promotional block shown on the homepage if the "Promos" module is enabled.  Use it to advertise or announce anything of primary importance to your audience.</p>

<%= link_to 'New promo', new_promo_path %>

<p>Choose promo to display on homepage: <br />

<% form_for(@setting) do |f| %>
  
<%= f.collection_select :promo_id, Promo.find(:all, :order => "created_at DESC"), :id, :title, :prompt => true %>
 
    <%= f.submit "Update" %>
<% end %></p>

<p></p>
<table>
  <tr>
    <th>Title</th>
  </tr>

<% for promo in @promos %>
  <tr>
    <td><%=h promo.title %></td>
    <td><%= link_to 'Show', promo %></td>
    <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
    <td><%= link_to 'Destroy', promo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/promos/new.html.erb
<% @page_title = "New Promo" %>

<%= javascript_include_tag :fckeditor %>

<h1>New promo</h1>

  <% if params[:preview_button] %>
    <%= render :partial => @promo %>
  <% end %>

<%= error_messages_for :promo %>

<% form_for(@promo) do |f| %>
  <p>
		<%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

    <%= fckeditor_tag("promo", "body", :height => "450px", :width => "560px") %>
    
  <p>
      <%= f.submit "Preview", :name => "preview_button" %>
      <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<% @page_title = @promo.title %>
<%= render :partial => @promo %>

<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>