config/routes.rb
WRS::Application.routes.draw do

  resources :downloads, :collection => {:report => :get}
  
  resources :show_reports

  resources :styles, :member => {:export => :get},
    :collection => {:import => :post, :import => :get}

  resources :songs

  resources :songs

  resources :web_profiles

  resources :pages

  resources :members

  resources :promos

  resources :settings, :except => [:edit, :show]

  resources :fans, :collection => {:import => :post, :tag => :post, :import => :get, :export => :get}

  resources :venues

  resources :shows
  
  resources :comments

  resources :blogs, :member => {:unsubscribe => :get}

  resources :mails, :member => {:deliver => :put, :select => :get}

  resources :lyrics

  resources :entries

  resources :comments
  
  resources :sessions
  
  resources :users

  resources :blogs

  resources :fans

  resources :songs

  root :to => 'about#index'

end

app/controllers/about_controller.rb
require 'rss/2.0'
require 'open-uri'

class AboutController < ApplicationController
  before_filter :show_videos?, :only => [:videos]
  
  def index    
    #@playlist = YouTube::Playlist.new(:id => "B407200BFFDB8F1E")
    @body_style = "home"
    @blogs = Blog.order('posted_at DESC, created_at DESC').paginate(:per_page => 10, :page => params[:page]) if @global_settings.show_blog?
    if @global_settings.show_news?
      @entries = Entry.find(:all, :offset => 1, :limit => 3, :order => "created_at DESC")  
      @first_entry = Entry.find(:all,  :limit => 1, :order => "created_at DESC")
    end
  end
  
  def rss
    blogs = @global_settings.show_blog? ? Blog.active.posted_yet.find(:all, :order => "posted_at DESC, created_at DESC") : []
    entries = @global_settings.show_news? ? Entry.find(:all, :order => "created_at DESC") : []
    lyrics = @global_settings.show_lyrics? ? Lyric.find(:all, :order => "created_at DESC") : []
    videos = @global_settings.show_videos? ? YouTube::User.new(:id => @global_settings.youtube_profile).videos : []
    items = blogs + entries + lyrics + videos
    @items = items.sort do |x,y|
      (y[:posted_at] || y[:created_at]) <=> (x[:posted_at] || x[:created_at])
    end
    render :template => 'about/rss.rss.builder'
  end
  
  def videos
    #@wrs = YouTube::User.new(:id => @global_settings.youtube_profile)
    @videos = @wrs.videos[0..9]
    unless @global_settings.featured_playlist.blank?
      @featured_videos = YouTube::Playlist.new(:id => @global_settings.featured_playlist) 
      @latest_demo = @featured_videos.videos[0]
    end
  end
  
  private
  
  def show_videos?
    render_404 unless @global_settings.show_videos? || admin?
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/_web.html.erb
<h3><%= @global_settings.artist_name %> on the Web</h3>

<%= @global_settings.on_the_web %>

app/views/about/index.html.erb
  
  <!-- PROMO -->
  <% if @global_settings.show_promo? && @global_settings.promo %>
    <div  id="promo">   
      <%= @global_settings.promo.body %>
    </div> <!-- end DIV "promo" -->
  <% end %>
  <!-- END PROMO -->
  
    
  <!-- NEWS -->
  <% if @global_settings.show_news? && !@first_entry.blank? %>
  <div id="news">
    <%= header "News", entries_path %>    
    <% for @entry in @first_entry %>
      <%= render :partial => @entry, :locals => {:show_byline => true} %>
    <% end %>
    
    <div id="archive">
    <h2 id="latest_headlines">Latest headlines</h2>
      <% for entry in @entries %> 
        <div class="entry">
            <h3 class="post_title"><%= link_to_unless_current entry.title, entry %></h3>
          <p class="byline">
            <%= @entry.created_at.strftime("%b %d %Y") %>
            <% if logged_in? %>
              (<%= link_to "edit", edit_entry_path(entry) %> | <%= link_to 'delete', entry, :confirm => 'Are you sure?', :method => :delete %>)
            <% end %>
          </p>
        </div> <!-- end DIV "entry" -->
      <% end %>    
    <p class="archive_link"><%= link_to "news archive...", entries_path %> </p>
  </div> <!-- end DIV "archive" -->
</div> <!-- end DIV "news" -->
  <% end %>
  <!-- END NEWS -->
  
  <!-- BLOG -->
  <% if @global_settings.show_blog? && !@blogs.empty? %>
  <div id="blog">
    <%= header "Blog", blogs_path %>    
    <% for @blog in @blogs %>          
        <%= render :partial => @blog, :locals => {:show_byline => true} %>    
    <% end %>    
    <p class="archive_link"><%= link_to "blog archive...", blogs_path %></p>
  </div> <!-- end DIV "blog" -->
  <% end %>
  <!-- END BLOG -->

app/views/about/music.html.erb
<% @page_title = "Music" %>

<div  id="music">
  <h2>Music</h2>
  
  <p>In November we went into the studio with "Comfortable Billy" Leger and recorded "Panic".  Here it is:</p>
  <dl class="music">
      <dt class="music_player"><%= link_to "Panic", mp3_link("panic") %></dt>
      <dd><%= music_player("panic", 1) %></dd>
  </dl>
    
  <p>Before we started playing out as much, we devoted more time to home recording.  Here are our first few recordings:</p>  
	<dl class="music">
    <dt><%= link_to "Sylvia", mp3_link("sylvia") %></dt>
    <dd class="music_player"><%= music_player("sylvia", 2) %></dd>
    <dt><%= link_to "Heartbreaker", mp3_link("heartbreaker") %></dt>
    <dd class="music_player"><%= music_player("heartbreaker", 2) %></dd>
    <dt><%= link_to "Potential", mp3_link("potential") %></dt>
    <dd class="music_player"><%= music_player("potential", 3) %></dd>
	</dl>
</div> <!-- end DIV "music" -->

app/views/about/videos.html.erb
<% @page_title = "Videos" %>
  
<div id="videos_main">
 
  <%= video(:video => @latest_demo, :heading => "Our latest demo video:") if @latest_demo %>

<p>You can see all our videos on <%= link_to "YouTube", "http://www.youtube.com/#{@global_settings.youtube_profile}" %>.</p>


<p>Here are our latest videos:</p>

<% for video in @videos %>
<div class="video">
  
<h4><%= link_to video.title, video.link %></h4>
<%= youtube :full_video => video.url %>


</div> <!-- end DIV "video" -->
<% end %>
</div> <!-- end DIV "videos_main" -->

app/views/about/web.html.erb
<% @page_title = "On the Web" %>


<%= render :partial => 'web' %>